services:
  api:
    restart: always
    environment:
      NODE_ENV: production
      PUBLISH_LIFECYCLE_EVENTS: "0"
    deploy:
      resources:
        limits:
          memory: 512M

  verifier:
    restart: always
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          memory: 512M

  generator:
    restart: always
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          memory: 1G

  orchestrator:
    restart: always
    environment:
      NODE_ENV: production
      PUBLISH_LIFECYCLE_EVENTS: "1"
    deploy:
      resources:
        limits:
          memory: 256M

  postgres:
    restart: always

  redis:
    restart: always
